[package]
name = "nscratch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
dirs = "6.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
